### ISSUE TITLE
Could not authenticate in-request, auth signature : Signature verification failed

### ISSUE THREAD

**Issue by devops1107** [juampynr/walmart-api-v2-php#1]
Hi , Thanks for your script.
I have try with your script but Signature is failed.
Thanks

![image](https://user-images.githubusercontent.com/59371147/120768249-85551a00-c54e-11eb-8598-8aa1e612489f.png)

**Comment by juampynr** [comment]
Hi @devops1107 !

I am sorry but I have no idea why you are getting this error. Did you figure it out?
